frontend:
  - changed-files:
      - any-glob-to-any-file: frontend/**/*

backend:
  - changed-files:
      - any-glob-to-any-file: backend/**/*

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - frontend/package.json
          - frontend/bun.lock
          - backend/go.mod
          - backend/go.sum

ci:
  - changed-files:
      - any-glob-to-any-file: .github/**/*

docs:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"
